apiVersion: batch/v1
kind: Job
metadata:
  name: db-job
spec:
  template:
    spec:
      containers:
        - name: db-job
          image: public.ecr.aws/w8x4g9h7/roboshop-v3/schema-load
          envFrom:
            - configMapRef:
                name: { { .Values.appName } }
      restartPolicy: Never
  backoffLimit: 2
