name: helm Destroy
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: 
  workflow_dispatch:
    inputs:
      appType:
        required: true
        type: string
      appName:
        required: true
        type: string
    secrets:
      vault_token:
        required: false
jobs:
  HelmDestroy:
    runs-on: self-hosted
    env: 
      vault_token: ${{ secrets.vault_token }}
    steps:
      - uses: actions/checkout@v4
      - name: Import Secrets Azure 
        uses: hashicorp/vault-action@v2.4.0
        with:
          url: http://vault-int.harshaldevops.online:8200
          token: ${{ secrets.vault_token }}
          secrets: |
            roboshop-infra/data/azure-sp ARM_CLIENT_ID | ARM_CLIENT_ID ;
            roboshop-infra/data/azure-sp ARM_CLIENT_SECRET | ARM_CLIENT_SECRET ;
            roboshop-infra/data/azure-sp ARM_SUBSCRIPTION_ID | ARM_SUBSCRIPTION_ID ;
            roboshop-infra/data/azure-sp ARM_TENANT_ID | ARM_TENANT_ID ;
      - name: helm Destroy
        run: |
          az login --service-principal --username $ARM_CLIENT_ID --password $ARM_CLIENT_SECRET --tenant $ARM_TENANT_ID
          az aks get-credentials --name=main-dev --resource-group=roboshop-ukwest-dev --overwrite-existing
          helm uninstall ${{ inputs.appName }} -n app
